/*
 * Charles O'Neal
 * Assignment 2
 * This is the admin contol panel for the mini twitter project.  It is a
 * SINGLETON pattern that allows only one instance of the admin control panel
 */
package assignment2;

import java.util.ArrayList;
import java.util.List;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Charles
 */
public class AdminControlPanel extends javax.swing.JFrame {

   // SINGLETON PATTERN
   private static AdminControlPanel instance;
   /**
    * Creates new form AdminControlPanel
    */
   List<User> userList;
   private AdminControlPanel() {
      initComponents();
      userList = new ArrayList<>();
   }
   
   public static AdminControlPanel getInstance() {
      if(instance == null) {
	 instance = new AdminControlPanel();
	 
      }
      return instance;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      userGroupPanel = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      userGroupTree = new javax.swing.JTree();
      buttonPannel = new javax.swing.JPanel();
      showPositivePercentageButton = new javax.swing.JButton();
      showMessagesTotalButton = new javax.swing.JButton();
      showGroupTotalButton = new javax.swing.JButton();
      showUserTotalButton = new javax.swing.JButton();
      openUserViewButton = new javax.swing.JButton();
      addUserButton = new javax.swing.JButton();
      addGroupButton = new javax.swing.JButton();
      jScrollPane2 = new javax.swing.JScrollPane();
      addUserTextArea = new javax.swing.JTextArea();
      jScrollPane3 = new javax.swing.JScrollPane();
      addGroupTextArea = new javax.swing.JTextArea();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Mini Twitter - Admin Control Panel");

      javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
      javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("John");
      treeNode1.add(treeNode2);
      treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Writers");
      javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Henry");
      treeNode2.add(treeNode3);
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Levi");
      treeNode2.add(treeNode3);
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ScreenWriters");
      javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Marcus");
      treeNode3.add(treeNode4);
      treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Leroy");
      treeNode3.add(treeNode4);
      treeNode2.add(treeNode3);
      treeNode1.add(treeNode2);
      treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gamers");
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ella");
      treeNode2.add(treeNode3);
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Lois");
      treeNode2.add(treeNode3);
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Phillip");
      treeNode2.add(treeNode3);
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("PS4");
      treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Curtis");
      treeNode3.add(treeNode4);
      treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Will");
      treeNode3.add(treeNode4);
      treeNode2.add(treeNode3);
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("PC");
      treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Manny");
      treeNode3.add(treeNode4);
      treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Erick");
      treeNode3.add(treeNode4);
      treeNode2.add(treeNode3);
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Xbox");
      treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Luis");
      treeNode3.add(treeNode4);
      treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Derek");
      treeNode3.add(treeNode4);
      treeNode2.add(treeNode3);
      treeNode1.add(treeNode2);
      treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mike");
      treeNode1.add(treeNode2);
      treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("David");
      treeNode1.add(treeNode2);
      treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Dion");
      treeNode1.add(treeNode2);
      treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Rick");
      treeNode1.add(treeNode2);
      treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("CS356");
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Helen");
      treeNode2.add(treeNode3);
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Daniel");
      treeNode2.add(treeNode3);
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Steve");
      treeNode2.add(treeNode3);
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Carl");
      treeNode2.add(treeNode3);
      treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Charles");
      treeNode2.add(treeNode3);
      treeNode1.add(treeNode2);
      userGroupTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
      jScrollPane1.setViewportView(userGroupTree);

      javax.swing.GroupLayout userGroupPanelLayout = new javax.swing.GroupLayout(userGroupPanel);
      userGroupPanel.setLayout(userGroupPanelLayout);
      userGroupPanelLayout.setHorizontalGroup(
         userGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userGroupPanelLayout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
            .addContainerGap())
      );
      userGroupPanelLayout.setVerticalGroup(
         userGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(userGroupPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
      );

      showPositivePercentageButton.setText("Show Positive Percentage");

      showMessagesTotalButton.setText("Show Messages Total");

      showGroupTotalButton.setText("Show Group Total");

      showUserTotalButton.setText("Show User Total");

      openUserViewButton.setText("Open User View");

      addUserButton.setText("Add User");
      addUserButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            addUserButtonActionPerformed(evt);
         }
      });

      addGroupButton.setText("Add Group");

      jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
      jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
      jScrollPane2.setHorizontalScrollBar(null);

      addUserTextArea.setColumns(20);
      addUserTextArea.setRows(5);
      jScrollPane2.setViewportView(addUserTextArea);

      jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
      jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

      addGroupTextArea.setColumns(20);
      addGroupTextArea.setRows(5);
      jScrollPane3.setViewportView(addGroupTextArea);

      jButton1.setText("User/Group Id Verification");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      jButton2.setText("Last Update");

      javax.swing.GroupLayout buttonPannelLayout = new javax.swing.GroupLayout(buttonPannel);
      buttonPannel.setLayout(buttonPannelLayout);
      buttonPannelLayout.setHorizontalGroup(
         buttonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPannelLayout.createSequentialGroup()
            .addContainerGap(19, Short.MAX_VALUE)
            .addGroup(buttonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPannelLayout.createSequentialGroup()
                  .addComponent(showMessagesTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(showPositivePercentageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(openUserViewButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(buttonPannelLayout.createSequentialGroup()
                  .addComponent(jScrollPane3)
                  .addGap(18, 18, 18)
                  .addComponent(addGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPannelLayout.createSequentialGroup()
                  .addComponent(jScrollPane2)
                  .addGap(18, 18, 18)
                  .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPannelLayout.createSequentialGroup()
                  .addGroup(buttonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPannelLayout.createSequentialGroup()
                        .addComponent(showUserTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                     .addGroup(buttonPannelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                  .addGroup(buttonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(showGroupTotalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))))
            .addContainerGap())
      );
      buttonPannelLayout.setVerticalGroup(
         buttonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(buttonPannelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(buttonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
               .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(buttonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(addGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
               .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addComponent(openUserViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(34, 34, 34)
            .addGroup(buttonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(buttonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(showGroupTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(showUserTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(buttonPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(showPositivePercentageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(showMessagesTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(userGroupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(buttonPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(userGroupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(buttonPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
      String str = addUserTextArea.getText();
      if(!str.equals("")) {
	 DefaultTreeModel model = (DefaultTreeModel)userGroupTree.getModel();
	 DefaultMutableTreeNode root = (DefaultMutableTreeNode)model.getRoot();
	 root.add(new DefaultMutableTreeNode(str));
	 model.reload(root);
	 addUserTextArea.setText("");
	 userList.add(new User(str));
	 
      } else {
	 showMessageDialog(getInstance(), "Please select a username");
	 
      }
   }//GEN-LAST:event_addUserButtonActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jButton1ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
	 for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	    if ("Nimbus".equals(info.getName())) {
	       javax.swing.UIManager.setLookAndFeel(info.getClassName());
	       break;
	    }
	 }
      } catch (ClassNotFoundException ex) {
	 java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
	 java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
	 java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	 java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
	 public void run() {
	    new AdminControlPanel().setVisible(true);
	 }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton addGroupButton;
   private javax.swing.JTextArea addGroupTextArea;
   private javax.swing.JButton addUserButton;
   private javax.swing.JTextArea addUserTextArea;
   private javax.swing.JPanel buttonPannel;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JButton openUserViewButton;
   private javax.swing.JButton showGroupTotalButton;
   private javax.swing.JButton showMessagesTotalButton;
   private javax.swing.JButton showPositivePercentageButton;
   private javax.swing.JButton showUserTotalButton;
   private javax.swing.JPanel userGroupPanel;
   private javax.swing.JTree userGroupTree;
   // End of variables declaration//GEN-END:variables
}
